In [1]:
%load_ext kedro.ipython

[04/06/26 16:01:03] INFO     Using                                                                  ]8;id=451126;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/framework/project/__init__.py\__init__.py]8;;\:]8;id=952132;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/framework/project/__init__.py#269\269]8;;\
                             '/Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python
                             3.11/site-packages/kedro/framework/project/rich_logging.yml' as
                             logging configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=539825;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=175413;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#64\64]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=424130;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=776685;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#66\66]8;;\

                    INFO     Resolved project path as:                                              ]8;id=14178;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=996716;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#181\181]8;;\
                             /Users/pathaoltd/Projects/telco-customer-churn-mlops.
                             To set a different path, run '%reload_kedro <project_root>'

[04/06/26 16:01:04] INFO     Kedro project telco-customer-churn-mlops                               ]8;id=85593;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=834074;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=46214;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=859040;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#148\148]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=752545;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=905377;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#154\154]8;;\

In [19]:
import pandas as pd

In [4]:
import sys
sys.path.append("src")

In [10]:
from telco_customer_churn_mlops.pipelines.ml_app.nodes_ml.hyperparameter_tuning import tune_xgb_pr_auc

In [11]:
X_train = catalog.load("X_train")

[04/06/26 16:08:04] INFO     Loading data from X_train (ParquetDataset)...                     ]8;id=380623;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=625511;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

In [12]:
X_train.head()

,gender,senior_citizen,partner,dependents,tenure,phone_service,online_security,online_backup,device_protection,tech_support,...,monthly_charges,multiple_lines,no_internet_service,dsl_internet_service,total_charges,contract_one_year,contract_two_year,payment_method_credit_card_automatic,payment_method_electronic_check,payment_method_mailed_check
3835,0,0,1,1,24,1,0,0,0,0,...,19.90,0,1,0,533.50,1,0,0,0,1
5394,0,0,1,0,48,1,0,1,0,1,...,105.10,1,0,0,5083.55,0,0,1,0,0
661,0,0,0,0,10,1,0,0,0,0,...,45.25,0,0,1,428.70,0,0,0,0,1
3092,0,0,0,0,1,0,0,0,0,0,...,25.10,0,0,1,25.10,0,0,0,0,1
2107,1,0,1,0,33,1,0,1,1,0,...,93.35,1,0,0,3092.00,0,0,0,1,0

In [13]:
y_train = catalog.load("y_train")

[04/06/26 16:08:18] INFO     Loading data from y_train (ParquetDataset)...                     ]8;id=596429;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=368212;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

In [14]:
y_train.head()

      churn
3835      0
5394      0
661       0
3092      1
2107      0

In [15]:
X_test = catalog.load("X_test")
y_test = catalog.load("y_test")

[04/06/26 16:09:12] INFO     Loading data from X_test (ParquetDataset)...                      ]8;id=918412;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=870535;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from y_test (ParquetDataset)...                      ]8;id=848174;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=598529;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

In [16]:
res = tune_xgb_pr_auc(
    X_train, y_train, X_test, y_test
)

[I 2026-04-06 16:10:18,976] A new study created in memory with name: no-name-43389466-3cf8-4d89-ae6e-ce59b30cb886
[W 2026-04-06 16:10:19,162] Trial 0 failed with parameters: {'n_estimators': 542, 'learning_rate': 0.05218325869158803, 'max_depth': 6, 'subsample': 0.6565693590469857, 'colsample_bytree': 0.5199841113905724, 'min_child_weight': 9, 'gamma': 0.15679707448519764, 'reg_alpha': 1.3112014210191063, 'reg_lambda': 1.164602145162713} because of the following error: XGBoostError("Invalid Parameter format for scale_pos_weight expect float but value='churn    2.768562\ndtype: float64'").
Traceback (most recent call last):
  File "/Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/Users/pathaoltd/Projects/telco-customer-churn-mlops/src/telco_customer_churn_mlops/pipelines/ml_app/nodes_ml/hyperparameter_tuning.py", line 68, in objective
    model.fit(X_train, y_train)
  File "/Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/core.py", line 751, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1806, in fit
    self._Booster = train(
                    ^^^^^^
  File "/Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/core.py", line 751, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/training.py", line 200, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2390, in update
    _check_call(
  File "/Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/core.py", line 324, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: Invalid Parameter format for scale_pos_weight expect float but value='churn    2.768562
dtype: float64'
[W 2026-04-06 16:10:19,167] Trial 0 failed with value None.

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 res = tune_xgb_pr_auc(                                                                       │
│   2 │   X_train, y_train, X_test, y_test                                                         │
│   3 )                                                                                            │
│   4                                                                                              │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/src/telco_customer_churn_mlops/pipelines/ml │
│ _app/nodes_ml/hyperparameter_tuning.py:73 in tune_xgb_pr_auc                                     │
│                                                                                                  │
│   70 │   │   return average_precision_score(y_valid, proba)                                      │
│   71 │                                                                                           │
│   72 │   study = optuna.create_study(direction="maximize")                                       │
│ ❱ 73 │   study.optimize(objective, n_trials=n_trials)                                            │
│   74 │                                                                                           │
│   75 │   # Train final model with best params                                                    │
│   76 │   best_params = study.best_params                                                         │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/optuna/s │
│ tudy/study.py:490 in optimize                                                                    │
│                                                                                                  │
│    487 │   │   │   RuntimeError:                                                                 │
│    488 │   │   │   │   If nested invocation of this method occurs.                               │
│    489 │   │   """                                                                               │
│ ❱  490 │   │   _optimize(                                                                        │
│    491 │   │   │   study=self,                                                                   │
│    492 │   │   │   func=func,                                                                    │
│    493 │   │   │   n_trials=n_trials,                                                            │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/optuna/s │
│ tudy/_optimize.py:68 in _optimize                                                                │
│                                                                                                  │
│    65 │                                                                                          │
│    66 │   try:                                                                                   │
│    67 │   │   if n_jobs == 1:                                                                    │
│ ❱  68 │   │   │   _optimize_sequential(                                                          │
│    69 │   │   │   │   study,                                                                     │
│    70 │   │   │   │   func,                                                                      │
│    71 │   │   │   │   n_trials,                                                                  │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/optuna/s │
│ tudy/_optimize.py:165 in _optimize_sequential                                                    │
│                                                                                                  │
│   162 │   │   │   │   break                                                                      │
│   163 │   │                                                                                      │
│   164 │   │   try:                                                                               │
│ ❱ 165 │   │   │   frozen_trial_id = _run_trial(study, func, catch)                               │
│   166 │   │   finally:                                                                           │
│   167 │   │   │   # The following line mitigates memory problems that can be occurred in some    │
│   168 │   │   │   # environments (e.g., services that use computing containers such as GitHub    │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/optuna/s │
│ tudy/_optimize.py:263 in _run_trial                                                              │
│                                                                                                  │
│   260 │   │   and func_err is not None                                                           │
│   261 │   │   and not isinstance(func_err, catch)                                                │
│   262 │   ):                                                                                     │
│ ❱ 263 │   │   raise func_err                                                                     │
│   264 │   return trial._trial_id                                                                 │
│   265                                                                                            │
│   266                                                                                            │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/optuna/s │
│ tudy/_optimize.py:206 in _run_trial                                                              │
│                                                                                                  │
│   203 │                                                                                          │
│   204 │   with get_heartbeat_thread(trial._trial_id, study._storage):                            │
│   205 │   │   try:                                                                               │
│ ❱ 206 │   │   │   value_or_values = func(trial)                                                  │
│   207 │   │   except exceptions.TrialPruned as e:                                                │
│   208 │   │   │   # TODO(mamu): Handle multi-objective cases.                                    │
│   209 │   │   │   state = TrialState.PRUNED                                                      │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/src/telco_customer_churn_mlops/pipelines/ml │
│ _app/nodes_ml/hyperparameter_tuning.py:68 in objective                                           │
│                                                                                                  │
│   65 │   │   }                                                                                   │
│   66 │   │                                                                                       │
│   67 │   │   model = XGBClassifier(**params)                                                     │
│ ❱ 68 │   │   model.fit(X_train, y_train)                                                         │
│   69 │   │   proba = model.predict_proba(X_valid)[:, 1]                                          │
│   70 │   │   return average_precision_score(y_valid, proba)                                      │
│   71                                                                                             │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/ │
│ core.py:751 in inner_f                                                                           │
│                                                                                                  │
│    748 │   │   │   │   warnings.warn(msg, FutureWarning)                                         │
│    749 │   │   │   for k, arg in zip(sig.parameters, args):                                      │
│    750 │   │   │   │   kwargs[k] = arg                                                           │
│ ❱  751 │   │   │   return func(**kwargs)                                                         │
│    752 │   │                                                                                     │
│    753 │   │   return inner_f                                                                    │
│    754                                                                                           │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/ │
│ sklearn.py:1806 in fit                                                                           │
│                                                                                                  │
│   1803 │   │   │   │   feature_types=feature_types,                                              │
│   1804 │   │   │   )                                                                             │
│   1805 │   │   │                                                                                 │
│ ❱ 1806 │   │   │   self._Booster = train(                                                        │
│   1807 │   │   │   │   params,                                                                   │
│   1808 │   │   │   │   train_dmatrix,                                                            │
│   1809 │   │   │   │   self.get_num_boosting_rounds(),                                           │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/ │
│ core.py:751 in inner_f                                                                           │
│                                                                                                  │
│    748 │   │   │   │   warnings.warn(msg, FutureWarning)                                         │
│    749 │   │   │   for k, arg in zip(sig.parameters, args):                                      │
│    750 │   │   │   │   kwargs[k] = arg                                                           │
│ ❱  751 │   │   │   return func(**kwargs)                                                         │
│    752 │   │                                                                                     │
│    753 │   │   return inner_f                                                                    │
│    754                                                                                           │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/ │
│ training.py:200 in train                                                                         │
│                                                                                                  │
│   197 │   for i in range(start_iteration, num_boost_round):                                      │
│   198 │   │   if cb_container.before_iteration(bst, i, dtrain, evals):                           │
│   199 │   │   │   break                                                                          │
│ ❱ 200 │   │   bst.update(dtrain, iteration=i, fobj=obj)                                          │
│   201 │   │   if cb_container.after_iteration(bst, i, dtrain, evals):                            │
│   202 │   │   │   break                                                                          │
│   203                                                                                            │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/ │
│ core.py:2390 in update                                                                           │
│                                                                                                  │
│   2387 │   │   self._assign_dmatrix_features(dtrain)                                             │
│   2388 │   │                                                                                     │
│   2389 │   │   if fobj is None:                                                                  │
│ ❱ 2390 │   │   │   _check_call(                                                                  │
│   2391 │   │   │   │   _LIB.XGBoosterUpdateOneIter(                                              │
│   2392 │   │   │   │   │   self.handle, ctypes.c_int(iteration), dtrain.handle                   │
│   2393 │   │   │   │   )                                                                         │
│                                                                                                  │
│ /Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/xgboost/ │
│ core.py:324 in _check_call                                                                       │
│                                                                                                  │
│    321 │   │   return value from API calls                                                       │
│    322 │   """                                                                                   │
│    323 │   if ret != 0:                                                                          │
│ ❱  324 │   │   raise XGBoostError(py_str(_LIB.XGBGetLastError()))                                │
│    325                                                                                           │
│    326                                                                                           │
│    327 def _check_distributed_params(kwargs: Dict[str, Any]) -> None:                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
XGBoostError: Invalid Parameter format for scale_pos_weight expect float but value='churn    2.768562
dtype: float64'

In [17]:
dir(y_train)

[
    'T',
    '_AXIS_LEN',
    '_AXIS_ORDERS',
    '_AXIS_TO_AXIS_NUMBER',
    '_HANDLED_TYPES',
    '__abs__',
    '__add__',
    '__and__',
    '__annotations__',
    '__array__',
    '__array_priority__',
    '__array_ufunc__',
    '__arrow_c_stream__',
    '__bool__',
    '__class__',
    '__contains__',
    '__copy__',
    '__dataframe__',
    '__dataframe_consortium_standard__',
    '__deepcopy__',
    '__delattr__',
    '__delitem__',
    '__dict__',
    '__dir__',
    '__divmod__',
    '__doc__',
    '__eq__',
    '__finalize__',
    '__floordiv__',
    '__format__',
    '__ge__',
    '__getattr__',
    '__getattribute__',
    '__getitem__',
    '__getstate__',
    '__gt__',
    '__hash__',
    '__iadd__',
    '__iand__',
    '__ifloordiv__',
    '__imod__',
    '__imul__',
    '__init__',
    '__init_subclass__',
    '__invert__',
    '__ior__',
    '__ipow__',
    '__isub__',
    '__iter__',
    '__itruediv__',
    '__ixor__',
    '__le__',
    '__len__',
    '__lt__',
    '__matmul__',
    '__mod__',
    '__module__',
    '__mul__',
    '__ne__',
    '__neg__',
    '__new__',
    '__nonzero__',
    '__or__',
    '__pandas_priority__',
    '__pos__',
    '__pow__',
    '__radd__',
    '__rand__',
    '__rdivmod__',
    '__reduce__',
    '__reduce_ex__',
    '__repr__',
    '__rfloordiv__',
    '__rmatmul__',
    '__rmod__',
    '__rmul__',
    '__ror__',
    '__round__',
    '__rpow__',
    '__rsub__',
    '__rtruediv__',
    '__rxor__',
    '__setattr__',
    '__setitem__',
    '__setstate__',
    '__sizeof__',
    '__str__',
    '__sub__',
    '__subclasshook__',
    '__truediv__',
    '__weakref__',
    '__xor__',
    '_accessors',
    '_accum_func',
    '_agg_examples_doc',
    '_agg_see_also_doc',
    '_align_for_op',
    '_align_frame',
    '_align_series',
    '_append',
    '_arith_method',
    '_arith_method_with_reindex',
    '_as_manager',
    '_attrs',
    '_box_col_values',
    '_can_fast_transpose',
    '_check_inplace_and_allows_duplicate_labels',
    '_check_is_chained_assignment_possible',
    '_check_label_or_level_ambiguity',
    '_check_setitem_copy',
    '_clear_item_cache',
    '_clip_with_one_bound',
    '_clip_with_scalar',
    '_cmp_method',
    '_combine_frame',
    '_consolidate',
    '_consolidate_inplace',
    '_construct_axes_dict',
    '_construct_result',
    '_constructor',
    '_constructor_from_mgr',
    '_constructor_sliced',
    '_constructor_sliced_from_mgr',
    '_create_data_for_split_and_tight_to_dict',
    '_data',
    '_deprecate_downcast',
    '_dir_additions',
    '_dir_deletions',
    '_dispatch_frame_op',
    '_drop_axis',
    '_drop_labels_or_levels',
    '_ensure_valid_index',
    '_find_valid_index',
    '_flags',
    '_flex_arith_method',
    '_flex_cmp_method',
    '_from_arrays',
    '_from_mgr',
    '_get_agg_axis',
    '_get_axis',
    '_get_axis_name',
    '_get_axis_number',
    '_get_axis_resolvers',
    '_get_block_manager_axis',
    '_get_bool_data',
    '_get_cleaned_column_resolvers',
    '_get_column_array',
    '_get_index_resolvers',
    '_get_item_cache',
    '_get_label_or_level_values',
    '_get_numeric_data',
    '_get_value',
    '_get_values_for_csv',
    '_getitem_bool_array',
    '_getitem_multilevel',
    '_getitem_nocopy',
    '_getitem_slice',
    '_gotitem',
    '_hidden_attrs',
    '_indexed_same',
    '_info_axis',
    '_info_axis_name',
    '_info_axis_number',
    '_info_repr',
    '_init_mgr',
    '_inplace_method',
    '_internal_names',
    '_internal_names_set',
    '_is_copy',
    '_is_homogeneous_type',
    '_is_label_or_level_reference',
    '_is_label_reference',
    '_is_level_reference',
    '_is_mixed_type',
    '_is_view',
    '_is_view_after_cow_rules',
    '_iset_item',
    '_iset_item_mgr',
    '_iset_not_inplace',
    '_item_cache',
    '_iter_column_arrays',
    '_ixs',
    '_logical_func',
    '_logical_method',
    '_maybe_align_series_as_frame',
    '_maybe_cache_changed',
    '_maybe_update_cacher',
    '_metadata',
    '_mgr',
    '_min_count_stat_function',
    '_needs_reindex_multi',
    '_pad_or_backfill',
    '_protect_consolidate',
    '_reduce',
    '_reduce_axis1',
    '_reindex_axes',
    '_reindex_multi',
    '_reindex_with_indexers',
    '_rename',
    '_replace_columnwise',
    '_repr_data_resource_',
    '_repr_fits_horizontal_',
    '_repr_fits_vertical_',
    '_repr_html_',
    '_repr_latex_',
    '_reset_cache',
    '_reset_cacher',
    '_sanitize_column',
    '_series',
    '_set_axis',
    '_set_axis_name',
    '_set_axis_nocheck',
    '_set_is_copy',
    '_set_item',
    '_set_item_frame_value',
    '_set_item_mgr',
    '_set_value',
    '_setitem_array',
    '_setitem_frame',
    '_setitem_slice',
    '_shift_with_freq',
    '_should_reindex_frame_op',
    '_slice',
    '_stat_function',
    '_stat_function_ddof',
    '_take_with_is_copy',
    '_to_dict_of_blocks',
    '_to_latex_via_styler',
    '_typ',
    '_update_inplace',
    '_validate_dtype',
    '_values',
    '_where',
    'abs',
    'add',
    'add_prefix',
    'add_suffix',
    'agg',
    'aggregate',
    'align',
    'all',
    'any',
    'apply',
    'applymap',
    'asfreq',
    'asof',
    'assign',
    'astype',
    'at',
    'at_time',
    'attrs',
    'axes',
    'backfill',
    'between_time',
    'bfill',
    'bool',
    'boxplot',
    'churn',
    'clip',
    'columns',
    'combine',
    'combine_first',
    'compare',
    'convert_dtypes',
    'copy',
    'corr',
    'corrwith',
    'count',
    'cov',
    'cummax',
    'cummin',
    'cumprod',
    'cumsum',
    'describe',
    'diff',
    'div',
    'divide',
    'dot',
    'drop',
    'drop_duplicates',
    'droplevel',
    'dropna',
    'dtypes',
    'duplicated',
    'empty',
    'eq',
    'equals',
    'eval',
    'ewm',
    'expanding',
    'explode',
    'ffill',
    'fillna',
    'filter',
    'first',
    'first_valid_index',
    'flags',
    'floordiv',
    'from_dict',
    'from_records',
    'ge',
    'get',
    'groupby',
    'gt',
    'head',
    'hist',
    'iat',
    'idxmax',
    'idxmin',
    'iloc',
    'index',
    'infer_objects',
    'info',
    'insert',
    'interpolate',
    'isetitem',
    'isin',
    'isna',
    'isnull',
    'items',
    'iterrows',
    'itertuples',
    'join',
    'keys',
    'kurt',
    'kurtosis',
    'last',
    'last_valid_index',
    'le',
    'loc',
    'lt',
    'map',
    'mask',
    'max',
    'mean',
    'median',
    'melt',
    'memory_usage',
    'merge',
    'min',
    'mod',
    'mode',
    'mul',
    'multiply',
    'ndim',
    'ne',
    'nlargest',
    'notna',
    'notnull',
    'nsmallest',
    'nunique',
    'pad',
    'pct_change',
    'pipe',
    'pivot',
    'pivot_table',
    'plot',
    'pop',
    'pow',
    'prod',
    'product',
    'quantile',
    'query',
    'radd',
    'rank',
    'rdiv',
    'reindex',
    'reindex_like',
    'rename',
    'rename_axis',
    'reorder_levels',
    'replace',
    'resample',
    'reset_index',
    'rfloordiv',
    'rmod',
    'rmul',
    'rolling',
    'round',
    'rpow',
    'rsub',
    'rtruediv',
    'sample',
    'select_dtypes',
    'sem',
    'set_axis',
    'set_flags',
    'set_index',
    'shape',
    'shift',
    'size',
    'skew',
    'sort_index',
    'sort_values',
    'squeeze',
    'stack',
    'std',
    'style',
    'sub',
    'subtract',
    'sum',
    'swapaxes',
    'swaplevel',
    'tail',
    'take',
    'to_clipboard',
    'to_csv',
    'to_dict',
    'to_excel',
    'to_feather',
    'to_gbq',
    'to_hdf',
    'to_html',
    'to_json',
    'to_latex',
    'to_markdown',
    'to_numpy',
    'to_orc',
    'to_parquet',
    'to_period',
    'to_pickle',
    'to_records',
    'to_sql',
    'to_stata',
    'to_string',
    'to_timestamp',
    'to_xarray',
    'to_xml',
    'transform',
    'transpose',
    'truediv',
    'truncate',
    'tz_convert',
    'tz_localize',
    'unstack',
    'update',
    'value_counts',
    'values',
    'var',
    'where',
    'xs'
]

In [23]:
y_train['churn'].values

array([0, 0, 0, ..., 0, 0, 0], shape=(5634,))