In [59]:
%reload_ext kedro.ipython
# %load_ext kedro.ipython

[04/07/26 12:58:08] INFO     Registered line magic '%reload_kedro'                                   ]8;id=650693;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=749651;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#64\64]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=723522;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=784285;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#66\66]8;;\

                    INFO     Resolved project path as:                                              ]8;id=469297;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=680248;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#181\181]8;;\
                             /Users/pathaoltd/Projects/telco-customer-churn-mlops.
                             To set a different path, run '%reload_kedro <project_root>'

                    INFO     Kedro project telco-customer-churn-mlops                               ]8;id=661011;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=940795;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=524760;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=617189;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#148\148]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=154457;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=143930;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/ipython/__init__.py#154\154]8;;\

In [21]:
X_train = catalog.load("X_train")
X_calib = catalog.load("X_calib")
X_test = catalog.load("X_test")
y_calib = catalog.load('y_calib')

[04/07/26 12:38:45] INFO     Loading data from X_train (ParquetDataset)...                     ]8;id=403462;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=459521;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from X_calib (ParquetDataset)...                     ]8;id=266177;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=934737;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from X_test (ParquetDataset)...                      ]8;id=286501;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=908718;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from y_calib (PickleDataset)...                      ]8;id=831273;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=906407;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

In [22]:
X_train.shape, X_test.shape, X_calib.shape

((4923, 23), (1055, 23), (1055, 23))

In [23]:
ops = catalog.load('optuna_search')

[04/07/26 12:38:54] INFO     Loading data from optuna_search (PickleDataset)...                ]8;id=935585;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=883491;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

In [24]:
ops.study_.direction

<StudyDirection.MAXIMIZE: 2>

In [25]:
ops.study_.best_value

0.6741173080869893

In [26]:
ops.study_.sampler

<optuna.samplers._tpe.sampler.TPESampler object at 0x135f5ded0>

In [27]:
ops.study_.pruner

<optuna.pruners._median.MedianPruner object at 0x124a068d0>

In [31]:
calib_model = catalog.load('calibrated_model')

[04/07/26 12:40:14] INFO     Loading data from calibrated_model (PickleDataset)...             ]8;id=503457;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=910938;file:///Users/pathaoltd/Projects/telco-customer-churn-mlops/.venv/lib/python3.11/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

In [32]:
calib_model

VennAbersCalibrator(cv='prefit',
                    estimator=XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=0.6248607949610526,
                                            device=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval_metric='aucpr',
                                            feature_types=None,
                                            feature_weights=None,
                                            gamma=4.33705614742331,
                                            grow_policy=None,
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=0.03314405599016941,
                                            max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=3,
                                            max_leaves=None,
                                            min_child_weight=14, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=500, n_jobs=-1,
                                            num_parallel_tree=None, ...),
                    inductive=False, random_state=1071)

In [43]:
import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)

In [63]:
from telco_customer_churn_mlops.pipelines.ml_app.nodes_ml.threshold_tuning import tune_threshold

In [38]:
scores = calib_model.predict_proba(X_calib)[:, 1]

In [39]:
scores

array([0.35051546, 0.5777027 , 0.02254165, ..., 0.35955056, 0.03756124,
       0.04029589], shape=(1055,))

In [42]:
thresholds = np.linspace(0, 1, 101)

In [48]:
results = []
pos_label = 1
zero_division = 0

for t in thresholds:
        y_pred = (scores >= t).astype(int)

        tn, fp, fn, tp = confusion_matrix(y_calib, y_pred).ravel()

        fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
        tpr = tp / (tp + fn) if (tp + fn) > 0 else 0.0

        results.append({
            "threshold": float(t),
            "precision": precision_score(y_calib, y_pred, pos_label=pos_label, zero_division=zero_division),
            "recall": recall_score(y_calib, y_pred, pos_label=pos_label, zero_division=zero_division),
            "f1": f1_score(y_calib, y_pred, pos_label=pos_label, zero_division=zero_division),
            "tpr": tpr,
            "fpr": fpr,
            "accuracy": accuracy_score(y_calib, y_pred),
        })

In [50]:
df = pd.DataFrame(results)
df.query("recall >= 0.80")

    threshold  precision    recall        f1       tpr       fpr  accuracy
0        0.00   0.264455  1.000000  0.418291  1.000000  1.000000  0.264455
1        0.01   0.264455  1.000000  0.418291  1.000000  1.000000  0.264455
2        0.02   0.268269  1.000000  0.423048  1.000000  0.980670  0.278673
3        0.03   0.299136  0.992832  0.459751  0.992832  0.836340  0.382938
4        0.04   0.307095  0.992832  0.469094  0.992832  0.805412  0.405687
5        0.05   0.350968  0.974910  0.516129  0.974910  0.648196  0.516588
6        0.06   0.352332  0.974910  0.517602  0.974910  0.644330  0.519431
7        0.07   0.354628  0.974910  0.520076  0.974910  0.637887  0.524171
8        0.08   0.357424  0.974910  0.523077  0.974910  0.630155  0.529858
9        0.09   0.359313  0.974910  0.525097  0.974910  0.625000  0.533649
10       0.10   0.367347  0.967742  0.532544  0.967742  0.599227  0.550711
11       0.11   0.371389  0.967742  0.536779  0.967742  0.588918  0.558294
12       0.12   0.463551  0.888889  0.609337  0.888889  0.369845  0.698578
13       0.13   0.475822  0.881720  0.618090  0.881720  0.349227  0.711848
14       0.14   0.477670  0.881720  0.619647  0.881720  0.346649  0.713744
15       0.15   0.478599  0.881720  0.620429  0.881720  0.345361  0.714692
16       0.16   0.479532  0.881720  0.621212  0.881720  0.344072  0.715640
17       0.17   0.486111  0.878136  0.625798  0.878136  0.333763  0.722275
18       0.18   0.487078  0.878136  0.626598  0.878136  0.332474  0.723223
19       0.19   0.523385  0.842294  0.645604  0.842294  0.275773  0.755450
20       0.20   0.524554  0.842294  0.646492  0.842294  0.274485  0.756398
21       0.21   0.524554  0.842294  0.646492  0.842294  0.274485  0.756398
22       0.22   0.524554  0.842294  0.646492  0.842294  0.274485  0.756398
23       0.23   0.524554  0.842294  0.646492  0.842294  0.274485  0.756398
24       0.24   0.525727  0.842294  0.647383  0.842294  0.273196  0.757346
25       0.25   0.526906  0.842294  0.648276  0.842294  0.271907  0.758294
26       0.26   0.526906  0.842294  0.648276  0.842294  0.271907  0.758294
27       0.27   0.528090  0.842294  0.649171  0.842294  0.270619  0.759242
28       0.28   0.528090  0.842294  0.649171  0.842294  0.270619  0.759242
29       0.29   0.528090  0.842294  0.649171  0.842294  0.270619  0.759242
30       0.30   0.528090  0.842294  0.649171  0.842294  0.270619  0.759242
31       0.31   0.531963  0.835125  0.649930  0.835125  0.264175  0.762085
32       0.32   0.533181  0.835125  0.650838  0.835125  0.262887  0.763033
33       0.33   0.533181  0.835125  0.650838  0.835125  0.262887  0.763033
34       0.34   0.533181  0.835125  0.650838  0.835125  0.262887  0.763033
35       0.35   0.533181  0.835125  0.650838  0.835125  0.262887  0.763033

In [64]:
from telco_customer_churn_mlops.pipelines.ml_app.nodes_ml.threshold_tuning import _evaluate_thresholds

In [65]:
_evaluate_thresholds(calib_model, X_calib, y_calib)

     threshold  precision    recall        f1       tpr       fpr  accuracy
0         0.00   0.264455  1.000000  0.418291  1.000000  1.000000  0.264455
1         0.01   0.264455  1.000000  0.418291  1.000000  1.000000  0.264455
2         0.02   0.268269  1.000000  0.423048  1.000000  0.980670  0.278673
3         0.03   0.299136  0.992832  0.459751  0.992832  0.836340  0.382938
4         0.04   0.307095  0.992832  0.469094  0.992832  0.805412  0.405687
..         ...        ...       ...       ...       ...       ...       ...
96        0.96   0.000000  0.000000  0.000000  0.000000  0.000000  0.735545
97        0.97   0.000000  0.000000  0.000000  0.000000  0.000000  0.735545
98        0.98   0.000000  0.000000  0.000000  0.000000  0.000000  0.735545
99        0.99   0.000000  0.000000  0.000000  0.000000  0.000000  0.735545
100       1.00   0.000000  0.000000  0.000000  0.000000  0.000000  0.735545

[101 rows x 7 columns]